version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST1*"

formatters:
  enable:
    - gofmt
