import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = 'badges/trophy-case.json';
const target = 'src/components/prs/confidenceBadges.ts';

const FORBIDDEN = [/<script/i, /<text/i, /<image/i, /\swidth=/i, /\sheight=/i, /"/];

const { badges } = JSON.parse(readFileSync(resolve(root, source), 'utf8'));

const sorted = [...badges].sort((a, b) => a.score - b.score);
sorted.forEach((badge, i) => {
  if (badge.score !== i) throw new Error(`expected score ${i}, got ${badge.score}`);
  if (!badge.svg.includes("viewBox='0 0 64 64'")) throw new Error(`badge ${i}: viewBox is not 0 0 64 64`);
  for (const re of FORBIDDEN) {
    if (re.test(badge.svg)) throw new Error(`badge ${i}: svg matches forbidden pattern ${re}`);
  }
  for (const [, id] of badge.svg.matchAll(/\sid='([^']+)'/g)) {
    if (!id.startsWith(`g${i}-`)) throw new Error(`badge ${i}: id ${id} is not prefixed g${i}-`);
  }
});

const entries = sorted
  .map(
    (b) => `  {
    score: ${b.score},
    name: ${JSON.stringify(b.name)},
    rankWord: ${JSON.stringify(b.rank_word)},
    tagline: ${JSON.stringify(b.tagline)},
    svg: ${JSON.stringify(b.svg)},
  },`
  )
  .join('\n');

const out = `// Generated by scripts/gen-badges.mjs from ${source}; do not edit by hand.

export interface ConfidenceBadge {
  score: number;
  name: string;
  rankWord: string;
  tagline: string;
  svg: string;
}

export const CONFIDENCE_BADGES: readonly ConfidenceBadge[] = [
${entries}
];
`;

writeFileSync(resolve(root, target), out);
console.log(`wrote ${target} (${sorted.length} badges)`);
