package db

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"time"
)

// JSONStringArray is a custom type for JSON array storage (SQLite compatible)
type JSONStringArray []string

// Scan implements the sql.Scanner interface
func (j *JSONStringArray) Scan(value interface{}) error {
	if value == nil {
		*j = []string{}
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		str, ok := value.(string)
		if !ok {
			return errors.New("JSONStringArray: invalid type")
		}
		bytes = []byte(str)
	}
	if len(bytes) == 0 {
		*j = []string{}
		return nil
	}
	return json.Unmarshal(bytes, j)
}

// Value implements the driver.Valuer interface
func (j JSONStringArray) Value() (driver.Value, error) {
	if j == nil {
		return "[]", nil
	}
	bytes, err := json.Marshal(j)
	if err != nil {
		return nil, err
	}
	return string(bytes), nil
}

// UserModel represents a user in the database (GORM model)
type UserModel struct {
	ID             uint       `gorm:"primaryKey;autoIncrement"`
	GitHubID       int64      `gorm:"column:github_id;uniqueIndex;not null"`
	GitHubUsername string     `gorm:"column:github_username;size:255;not null"`
	GitHubAvatar   string     `gorm:"column:github_avatar"`
	CreatedAt      time.Time  `gorm:"autoCreateTime"`
	LastLoginAt    *time.Time `gorm:"column:last_login_at;index"`
}

// TableName specifies the table name for UserModel
func (UserModel) TableName() string {
	return "users"
}

// SessionModel represents a user session (GORM model)
type SessionModel struct {
	ID        string    `gorm:"primaryKey;size:64"`
	UserID    uint      `gorm:"index;not null"`
	User      UserModel `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE"`
	ExpiresAt time.Time `gorm:"index;not null"`
	CreatedAt time.Time `gorm:"autoCreateTime"`
}

// TableName specifies the table name for SessionModel
func (SessionModel) TableName() string {
	return "sessions"
}

// PRModel represents a pull request in the database (GORM model)
type PRModel struct {
	ID              uint            `gorm:"primaryKey;autoIncrement"`
	RepoOwner       string          `gorm:"size:255;not null;uniqueIndex:idx_prs_unique"`
	RepoName        string          `gorm:"size:255;not null;uniqueIndex:idx_prs_unique"`
	PRNumber        int             `gorm:"not null;uniqueIndex:idx_prs_unique"`
	Title           string          `gorm:"type:text"`
	Author          string          `gorm:"size:255;index"`
	LastCommitSHA   string          `gorm:"size:40;not null"`
	Status          string          `gorm:"size:20;default:pending;index"`
	ReviewPath      string          `gorm:"column:review_path;type:text;index"`
	LastReviewedAt  *time.Time      `gorm:"index"`
	GeneratingSince *time.Time      `gorm:"index"`
	CreatedAt       *time.Time      `gorm:"index"`
	Draft           bool            `gorm:"default:false"`
	ApprovalCount   int             `gorm:"default:0"`
	MyReviewStatus  string          `gorm:"size:20"` // "APPROVED", "CHANGES_REQUESTED", "COMMENTED", or ""
	CIState         string          `gorm:"size:20;default:unknown"`
	CIFailedChecks  JSONStringArray `gorm:"type:text"`
	// GitHub PR state: "open", "closed", or "merged". Only diverges from
	// "open" on rows retained past close (manual claims) — everything else
	// is deleted at close by cleanup.
	PRState string `gorm:"column:pr_state;size:16;default:open"`
	// The latest review was generated by an agent that fell back to a
	// different model than requested. Written by MarkPRCompleted.
	ModelFallback bool `gorm:"column:model_fallback;default:false"`
	// ReviewRunID is indexed for telemetry correlation; ReviewRunJSON stores
	// the full additive payload.ReviewRunInfo without coupling db to payload.
	ReviewRunID   string `gorm:"column:review_run_id;size:36;index"`
	ReviewRunJSON string `gorm:"column:review_run_json;type:text"`
	// ProjectionRunID fences mutable PR status/result writes across overlapping
	// service instances. It records the most recent run allowed to project and
	// intentionally remains set after that run becomes terminal.
	ProjectionRunID string `gorm:"column:projection_run_id;size:36"`
	// Review importance counts (populated after review generation)
	CriticalCount int `gorm:"default:0"`
	MediumCount   int `gorm:"default:0"`
	LowCount      int `gorm:"default:0"`
	// Overall review verdict parsed from the SUMMARY entry:
	// "request_changes", "approve_suggestions", "approve", or "" (unknown).
	// Written alongside the counts by MarkPRCompleted.
	ReviewVerdict string `gorm:"column:review_verdict;size:32"`
	// User notes (single-user mode)
	Notes string `gorm:"size:15"`
	// Poll economy: last seen updated_at from GitHub search API
	GitHubUpdatedAt *time.Time `gorm:"column:github_updated_at"`
	// Populated when Status=="error"; surfaced to the UI.
	ErrorMessage string `gorm:"column:error_message;type:text"`
	// How many times the auto-retry path has reset this PR back to pending
	// after an error. Capped by ResetErrorPRs so deterministic failures
	// (auth misconfig, model outage) don't burn quota indefinitely. Legacy
	// manual admission and successful completion reset it; run-aware automatic
	// admission intentionally preserves it so retries cannot re-arm themselves.
	ErrorRetryCount int `gorm:"column:error_retry_count;default:0"`
}

// TableName specifies the table name for PRModel
func (PRModel) TableName() string {
	return "prs"
}

// ReviewRunModel is the append-only identity/configuration record plus the
// mutable lifecycle projection for one execution. It deliberately does not
// own a cascading PR relationship: closed PR rows are routinely cleaned up,
// while review history must survive.
type ReviewRunModel struct {
	RunID             string `gorm:"column:run_id;primaryKey;size:36;index:idx_review_runs_pr_history,priority:5;index:idx_review_runs_commit_history,priority:5"`
	PRID              *uint  `gorm:"column:pr_id;index"`
	RepoOwner         string `gorm:"size:255;not null;index:idx_review_runs_pr_history,priority:1;index:idx_review_runs_commit_history,priority:1"`
	RepoName          string `gorm:"size:255;not null;index:idx_review_runs_pr_history,priority:2;index:idx_review_runs_commit_history,priority:2"`
	PRNumber          int    `gorm:"not null;index:idx_review_runs_pr_history,priority:3"`
	CommitSHA         string `gorm:"size:40;not null;index:idx_review_runs_commit_history,priority:3"`
	RequestedByUserID *uint  `gorm:"column:requested_by_user_id;index"`
	TriggerSource     string `gorm:"size:32;not null;index"`
	Status            string `gorm:"size:32;not null;index;index:idx_review_runs_status_lease,priority:1;index:idx_review_runs_status_queue,priority:1"`

	RequestedConfigJSON string `gorm:"column:requested_config_json;type:text;not null"`
	EffectiveConfigJSON string `gorm:"column:effective_config_json;type:text;not null"`
	ConfigSourcesJSON   string `gorm:"column:config_sources_json;type:text;not null"`
	ConfigHash          string `gorm:"column:config_hash;size:64;not null;index"`
	ConfigSchemaVersion int    `gorm:"column:config_schema_version;not null"`

	AgentBackend      string `gorm:"column:agent_backend;size:32;index"`
	AgentModel        string `gorm:"column:agent_model;size:255;index"`
	AgentEffort       string `gorm:"column:agent_effort;size:32"`
	AgentWallClockSec int    `gorm:"column:agent_wall_clock_sec"`
	AgentMaxTurns     int    `gorm:"column:agent_max_turns"`

	AcceptedAt  time.Time  `gorm:"column:accepted_at;not null;index;index:idx_review_runs_pr_history,priority:4;index:idx_review_runs_commit_history,priority:4"`
	QueuedAt    time.Time  `gorm:"column:queued_at;not null;index;index:idx_review_runs_status_queue,priority:2"`
	StartedAt   *time.Time `gorm:"column:started_at;index"`
	CompletedAt *time.Time `gorm:"column:completed_at;index"`
	DurationMS  int64      `gorm:"column:duration_ms"`

	HTMLPath                 string `gorm:"column:html_path;type:text"`
	JSONPath                 string `gorm:"column:json_path;type:text"`
	CriticalCount            int    `gorm:"column:critical_count"`
	MediumCount              int    `gorm:"column:medium_count"`
	LowCount                 int    `gorm:"column:low_count"`
	Verdict                  string `gorm:"size:32"`
	ModelFallback            bool   `gorm:"column:model_fallback;default:false;index"`
	ServingModelVerification string `gorm:"column:serving_model_verification;size:16"`
	ActualModelsJSON         string `gorm:"column:actual_models_json;type:text"`
	PublicationStatus        string `gorm:"column:publication_status;size:32"`

	TerminalCode string `gorm:"column:terminal_code;size:64;index"`
	FailureStage string `gorm:"column:failure_stage;size:64"`
	ErrorSummary string `gorm:"column:error_summary;type:text"`

	ServiceRevision    string     `gorm:"column:service_revision;size:255"`
	LeaseHolder        string     `gorm:"column:lease_holder;size:255;index"`
	LeaseExpiresAt     *time.Time `gorm:"column:lease_expires_at;index;index:idx_review_runs_status_lease,priority:2"`
	ExecutionAttempt   int        `gorm:"column:execution_attempt;default:0"`
	IdempotencyScope   string     `gorm:"column:idempotency_scope;size:255;uniqueIndex:idx_review_runs_idempotency,where:idempotency_key_hash <> '',priority:1"`
	IdempotencyKeyHash string     `gorm:"column:idempotency_key_hash;size:64;uniqueIndex:idx_review_runs_idempotency,where:idempotency_key_hash <> '',priority:2"`
	RequestHash        string     `gorm:"column:request_hash;size:64"`
	CreatedAt          time.Time  `gorm:"autoCreateTime"`
	UpdatedAt          time.Time  `gorm:"autoUpdateTime"`
}

func (ReviewRunModel) TableName() string { return "review_runs" }

// ReviewStageAttemptModel records provider-level execution details without
// forcing the evolving long-tail of model metadata into review_runs columns.
type ReviewStageAttemptModel struct {
	ID                   uint            `gorm:"primaryKey;autoIncrement"`
	RunID                string          `gorm:"column:run_id;size:36;not null;uniqueIndex:idx_review_stage_attempt_unique,priority:1"`
	ExecutionAttempt     int             `gorm:"column:execution_attempt;not null;uniqueIndex:idx_review_stage_attempt_unique,priority:2"`
	Stage                string          `gorm:"size:64;not null;uniqueIndex:idx_review_stage_attempt_unique,priority:3;index:idx_review_stage_attempt_model,priority:1"`
	InvocationNumber     int             `gorm:"column:invocation_number;not null;uniqueIndex:idx_review_stage_attempt_unique,priority:4"`
	AttemptNumber        int             `gorm:"column:attempt_number;not null;uniqueIndex:idx_review_stage_attempt_unique,priority:5"`
	Provider             string          `gorm:"size:64;index"`
	Backend              string          `gorm:"size:64;index:idx_review_stage_attempt_model,priority:2"`
	RequestedModel       string          `gorm:"column:requested_model;size:255;index:idx_review_stage_attempt_model,priority:3"`
	ResolvedModel        string          `gorm:"column:resolved_model;size:255"`
	ObservedServedModels JSONStringArray `gorm:"column:observed_served_models;type:text"`
	PrimaryServedModel   string          `gorm:"column:primary_served_model;size:255"`
	ServedModelSource    string          `gorm:"column:served_model_source;size:32"`
	ServingModelVerified bool            `gorm:"column:serving_model_verified;default:false"`
	Fallback             bool            `gorm:"default:false;index"`
	FallbackReason       string          `gorm:"column:fallback_reason;size:255"`
	MatcherVersion       string          `gorm:"column:matcher_version;size:32"`
	Effort               string          `gorm:"size:32"`
	Status               string          `gorm:"size:32;index"`
	AssistantTurns       int             `gorm:"column:assistant_turns"`
	InputTokens          int64           `gorm:"column:input_tokens"`
	OutputTokens         int64           `gorm:"column:output_tokens"`
	TotalTokens          int64           `gorm:"column:total_tokens"`
	StartedAt            *time.Time      `gorm:"column:started_at;index"`
	CompletedAt          *time.Time      `gorm:"column:completed_at"`
	DurationMS           int64           `gorm:"column:duration_ms"`
	StopReason           string          `gorm:"column:stop_reason;size:64"`
	ErrorCode            string          `gorm:"column:error_code;size:64"`
	ErrorSummary         string          `gorm:"column:error_summary;type:text"`
	CreatedAt            time.Time       `gorm:"autoCreateTime"`
	UpdatedAt            time.Time       `gorm:"autoUpdateTime"`
	ReviewRun            ReviewRunModel  `gorm:"foreignKey:RunID;references:RunID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
}

func (ReviewStageAttemptModel) TableName() string { return "review_stage_attempts" }

// UserPRViewModel represents the relationship between users and PRs (GORM model)
type UserPRViewModel struct {
	ID           uint            `gorm:"primaryKey;autoIncrement"`
	UserID       uint            `gorm:"uniqueIndex:idx_user_pr_unique;not null"`
	User         UserModel       `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE"`
	PRID         uint            `gorm:"column:pr_id;uniqueIndex:idx_user_pr_unique;not null"`
	PR           PRModel         `gorm:"foreignKey:PRID;constraint:OnDelete:CASCADE"`
	IsAuthor     bool            `gorm:"default:false"`
	IsReviewer   bool            `gorm:"default:false"`
	ViaTeams     JSONStringArray `gorm:"type:text"` // JSON array of team names
	ReviewStatus string          `gorm:"size:20"`   // "APPROVED", "CHANGES_REQUESTED", "COMMENTED", or ""
	Notes        string          `gorm:"size:15"`
	Hidden       bool            `gorm:"default:false"`
	// User-initiated "move to Hidden section" toggle. Distinct from Hidden,
	// which is a poller-managed soft delete that the poll cycle resets on
	// every upsert; UserHidden is only ever written by the user and must
	// never appear in a poller DoUpdates set.
	UserHidden bool `gorm:"column:user_hidden;default:false"`
	// The user requested a review for this PR by hand (generate-review).
	// Same write discipline as UserHidden: only the generate-review handler
	// writes it, never any poller DoUpdates or prune set. While true (and
	// not Hidden) it also exempts a closed PR from cleanup deletion.
	ViaManual bool `gorm:"column:via_manual;default:false"`
}

// TableName specifies the table name for UserPRViewModel
func (UserPRViewModel) TableName() string {
	return "user_pr_views"
}

// TelemetryEventModel represents a user interaction event (GORM model)
type TelemetryEventModel struct {
	ID        uint      `gorm:"primaryKey;autoIncrement"`
	UserID    uint      `gorm:"index;not null"`
	User      UserModel `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE"`
	Action    string    `gorm:"size:50;index;not null"`
	Label     string    `gorm:"size:255"`
	PROwner   string    `gorm:"size:255"`
	PRRepo    string    `gorm:"size:255"`
	PRNumber  int       `gorm:"default:0"`
	CreatedAt time.Time `gorm:"autoCreateTime;index"`
}

// TableName specifies the table name for TelemetryEventModel
func (TelemetryEventModel) TableName() string {
	return "telemetry_events"
}

// SettingModel represents a key-value setting (GORM model)
type SettingModel struct {
	Key   string `gorm:"primaryKey;size:255"`
	Value string `gorm:"type:text;not null"`
}

// TableName specifies the table name for SettingModel
func (SettingModel) TableName() string {
	return "settings"
}

// FindingOutcomeModel records a human triage decision on a single review
// finding (GORM model). One row per (owner, repo, pr, reviewed sha,
// fingerprint); re-deciding the same finding overwrites the row rather than
// appending history.
//
// This is forensics / label-harvest data, not enforcement: nothing blocks on
// an outcome, and rows are written only by an explicit user action. Outcome
// vocabulary: "dismissed" (not a bug — reason required), "acknowledged"
// (risk accepted), "unresolved" (explicitly marked still-open).
type FindingOutcomeModel struct {
	ID        uint   `gorm:"primaryKey;autoIncrement"`
	RepoOwner string `gorm:"size:255;not null;uniqueIndex:idx_finding_outcomes_unique"`
	RepoName  string `gorm:"size:255;not null;uniqueIndex:idx_finding_outcomes_unique"`
	PRNumber  int    `gorm:"not null;uniqueIndex:idx_finding_outcomes_unique"`
	// ReviewedSHA is the commit the review that surfaced the finding was
	// generated at (short or full, stored as given) — outcomes are per-SHA
	// so the harvest can join them against per-SHA sidecars.
	ReviewedSHA string `gorm:"size:40;not null;uniqueIndex:idx_finding_outcomes_unique"`
	// Fingerprint identifies the finding robustly across regenerations:
	// "<file>:<line/10>:<sha256(normalized comment prefix)[:12]>". Exact
	// line numbers drift between pushes and comment tails vary between
	// runs, so the line is bucketed and only a normalized comment prefix is
	// hashed. Computed server-side (see server.findingFingerprint).
	Fingerprint string `gorm:"size:512;not null;uniqueIndex:idx_finding_outcomes_unique"`
	// Provenance/Severity snapshot the finding's attribution at decision
	// time so the harvest can split FP rates per pass without re-reading
	// the sidecar.
	Provenance string    `gorm:"size:32"`
	Severity   string    `gorm:"size:16"`
	Outcome    string    `gorm:"size:16;not null"` // "dismissed", "acknowledged", "unresolved"
	Reason     string    `gorm:"type:text"`
	DecidedBy  string    `gorm:"size:255"`
	DecidedAt  time.Time `gorm:"not null;index"`
}

// TableName specifies the table name for FindingOutcomeModel
func (FindingOutcomeModel) TableName() string {
	return "finding_outcomes"
}
